// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRy5FK4DwLq0_DUINt1b9Gh5YN6Z3MBs',
    appId: '1:540561315487:web:60114fd67edb14251874aa',
    messagingSenderId: '540561315487',
    projectId: 'miss-you-ai-7a408',
    authDomain: 'miss-you-ai-7a408.firebaseapp.com',
    storageBucket: 'miss-you-ai-7a408.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmeYm4OcVtMqj8lqncfVClJ2SV-OmWOpY',
    appId: '1:540561315487:android:60ceaf186ca29a7d1874aa',
    messagingSenderId: '540561315487',
    projectId: 'miss-you-ai-7a408',
    storageBucket: 'miss-you-ai-7a408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3uY2SYnSNSXZeCK7Dn803iZSbdcMJz0',
    appId: '1:540561315487:ios:2cc5c4e03a2a7c311874aa',
    messagingSenderId: '540561315487',
    projectId: 'miss-you-ai-7a408',
    storageBucket: 'miss-you-ai-7a408.firebasestorage.app',
    iosBundleId: 'com.example.missYouAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj3uY2SYnSNSXZeCK7Dn803iZSbdcMJz0',
    appId: '1:540561315487:ios:2cc5c4e03a2a7c311874aa',
    messagingSenderId: '540561315487',
    projectId: 'miss-you-ai-7a408',
    storageBucket: 'miss-you-ai-7a408.firebasestorage.app',
    iosBundleId: 'com.example.missYouAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHRy5FK4DwLq0_DUINt1b9Gh5YN6Z3MBs',
    appId: '1:540561315487:web:bd506c3654e27ae91874aa',
    messagingSenderId: '540561315487',
    projectId: 'miss-you-ai-7a408',
    authDomain: 'miss-you-ai-7a408.firebaseapp.com',
    storageBucket: 'miss-you-ai-7a408.firebasestorage.app',
  );
}
